omega    = 0.0043;  % spec density dependent mortality
om0      = 0.0;     % density independent mortality
k00_0    = 0.04;    % spec light extinction by water 0.045 m-1 typical of HOT and BATS Malmstrom2010
k0       = k00_0;
kchl     = 0.04;    % spec light extinction by chl; 0.048 Fasham et al. 1990; 0.02-0.06 Riley 1956; 0.019 Aruga&Ichimura 1968
kchlv    = kchl*ones(1,5);
snew_rat = 30.;
alim     = 0.0;   % Not used?
A_N00    = 0.2;   % affinity (growth) nitrate uptake
A_N      = A_N00;
aff_I0   = 0.11;  % light affinity
aff_I    = aff_I0;
aff_I00  = aff_I0;
aff_Im   = 0.11;  % light affinity drifters
vg_trade_expo = 0.18;
%af_Im    = 3;
vr       = 0E-5;   % Not used? d/m^2 travel cost
vsink    = 0.5;    % swimming speed (will be regulated in most settings)
vs0      = vsink;  % initial travel speed
vsmS0    = 110;    % maximal sink or ascent velocity of phytoplankton cells, m/d
vsmaxb   = vsmS0;  % Walsby1978 Trichodesmium 11*24 m/d
vsmS     = vsmS0;
Q00      = 0.03;   % subsistence quota
Q0       = Q00;
Qmax     = 0.2;    % maximum quota TODO lower
Qpmax    = Qmax-Q0;
Pm0      = 0.67;   % maximum photosynthesis rate (1/d)
Pm = Pm0;
Pm_Im    = Pm0;    % maximum photosynthesis rate drifters
chl2c_min= 0.01;   % minmimum CHL:C 
chl2cf   = 0.1;    % N-specific CHL:C
crit     = 0.95;   % auxiliary coefficient in optimization
Q10f     = 1.7;    % temperature Q10 for mortality
Q10fm    = 2;      % Not used?  temperature Q10 for mortality
bdiff    = 4;      % 4/sqrt(Dt) equilibrium diffusion length
I_al     = 70;
trm      = 0;      % Not used?
trfac    = 1;      % Not used?
Tf       = 1;
Tfa=Tf; Tfm=Tf; temp=20;
ode      = 0;      % Not used?
maxC     = 30;
maxCv    = ones(5,1)*maxC;
pars     = [0.1 1.];
kN       = 0.18;
limf     = 1;      % Not used?
KzSu     = 3;%60 26 m2/d turbulent diffusion coefficient Osborn1980
KzWt     = 4000; %m2/d.T % times Temp : invernal mixing rate
Kz       = KzSu;
Tfma     = 1;      % Not used?
bmax     = 75;     % maximum half migration distance in optimization loop
cvc      = 0.1;    % critical std of NO3 for chemocline depth
no3gf    = 4.5;
no3k     = 0.3;
cloud    = 0.4;
carb0    = 1;
mixatt   = 1;   % relative enhancement of attenuation due to mixing (CDOM+POC)
zNcr     = 65;  % critical chemocline depth for migration hitting surface
vst      = 10;  % critical speed for physiological trade-offs
ve       = 1;   % strength of pyhsiology-speed trade-off
